# Plugin info
api-version: "1.12"
name: "${project.name}"
description: "${project.description}"
version: "${project.version}"
main: "${project.groupId}.${project.artifactId}.${project.name}"
database: false
depend: []
softdepend: []

# Authors
author: "Teddy"
authors: []
website: "https://twieteddy.github.io"

permissions:
  lovelyhugs.hug:
    default: op

commands:
  hug:
    description: Hug another player
    permission: lovelyhugs.hug
    aliases: []